services:
  epgo:
    container_name: epgo
    build:
      context: .
      args:
        # Or amd64
        - TARGETARCH=arm64
    environment:
      - TZ=America/Chicago
    volumes:
      # Assumes config.yaml is in the same directory as this docker-compose.yaml
      - ./config.yaml:/app/config.yaml
    command: -config /app/config.yaml
    restart: never
