version: "3.4"
services:
    guide2go:
      container_name: guide2go
      build: .
      ports:
        - 8180:8080
      environment:
        - TZ=America/Chicago
      volumes:
        - YOUR_CONFIG.YAML_FOLDER:/app/
        - YOUR_IMAGES_FOLDER:/app/images/
      restart: always