name: Development workflow

on:
  push:
    branches:
      - development

jobs:
  image-build-push-dev:
    runs-on: self-hosted
    steps:
      - name: Build the Docker image
        working-directory: ./${{ env.GITHUB_WORKSPACE }}
        run: |
          new_tag=$(date +%s)
          docker build . --tag chuchodavids/epgo:"$new_tag" --tag chuchodavids/epgo:development
          docker push chuchodavids/epgo:"$new_tag"
          docker push chuchodavids/epgo:development
