name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:
name: ci

on:
  push:
    branches: master


  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: go build
      run: go build -o guide2go
    -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag chuchodavids/guidetogo:$(date +%s)
    - name: push
      run: docker push chuchodavids/guidetogo:$(date +%s)
