name: Docker Image CI

on:
  push:
    branches: [ "master" ]
jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: go build
      run: go build . -o guide2go
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag guidetogo:$(date +%s)
