name: Stable Workflow

on:
  push:
    branches: 
     - master

jobs:
  image-build-push-prod:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        new_tag=$(date +%s)
        docker build . --file Dockerfile --tag chuchodavids/guide2go:"$new_tag" --tag chuchodavids/guide2go:stable --tag chuchodavids/guide2go:latest
        docker push chuchodavids/guide2go:"$new_tag"
        docker push chuchodavids/guide2go:stable
