name: Stable Workflow

on:
  push:
    branches: 
     - master
  pull_request:
    branches:
      - main  # Trigger on pull requests to the 'main' branch.
  workflow_dispatch:  # Allow manual triggering

jobs:
  image-build-push-prod:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true 
        tags: chuchodavids/guide2go:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}